[settings]
check_interval_sec = 3 # интервал обновления или интервал, с которым файлы перемещаются в указанные пути
min_stable_time_sec = 10 # сколько сек файл должен быть без изменений, чтобы он переместился
converter_idle_minutes = 30 # сколько мин папка должна быть без изменений, чтобы запустить конвертор
converter_folder_name = convert # папка где лежит конвертор с start.bat
converter_start_interval_min = 15 # с какой переодичностью запускать конверторы
sender_folder_name = BatToServer # папка запуска отправщика файлов на сервер с батником videoToServer.bat
check_settings_interval_min = 1 # проверка настроек, чтобы не перезапускать каждый раз скрипт


vpn_name = vpn # название VPN
vpn_user = bajana # логин для VPN
vpn_pass = KxS6y912video@p@$$ # пароль от VPN
vpn_check_interval_sec = 60 # интервал проверки VPN

max_workers = 1

[main]
main1 = L:\BackupFile # папка откуда перемещать скачанные видео
# main2 = 

[ips]
195.138.86.14 = D:\BackupFile        # Филатова
94.131.207.175 = D:\BackupFile       # Амстердам
85.198.150.198 = D:\BackupFile       # Аполло
91.243.199.127 = D:\BackupFile       # Черкассы

178.136.192.121 = E:\BackupFile      # Гагарин
185.132.1.213 = E:\BackupFile        # Глушко
194.28.5.67 = E:\BackupFile          # Сумы 2
176.241.137.38 = E:\BackupFile       # Григоренко

93.170.90.195 = F:\BackupFile        # Днепр
109.237.92.49 = F:\BackupFile        # Дрим
94.158.153.218 = F:\BackupFile       # Жуковского
85.159.3.109 = F:\BackupFile         # Здолбуновская

195.138.66.255 = G:\BackupFile       # Кадор 
77.222.159.34 = G:\BackupFile        # Левобережная
85.159.3.219 = G:\BackupFile         # Лобановского
91.220.235.171 = G:\BackupFile       # Метроград

212.90.162.213 = H:\BackupFile       # Днепр Караван
62.205.146.173 = H:\BackupFile       # Опера
94.131.244.109 = H:\BackupFile       # Оушен
94.154.222.131 = H:\BackupFile	     # Позняки

91.228.58.214 = I:\BackupFile        # Фонтан 1 
176.241.136.160 = I:\BackupFile      # РивГош
188.115.185.68 = I:\BackupFile       # Шампанский 
31.42.166.8 = I:\BackupFile	     # Каменец-Подольский

217.25.204.224 = J:\BackupFile       # Район
109.251.113.15 = J:\BackupFile       # Ретровиль
185.132.0.221 = J:\BackupFile        # Успенская
77.222.155.140 = J:\BackupFile       # Каменец-Подольский 2

91.220.235.168 = K:\BackupFile       # Метроград 2
195.64.232.172 = K:\BackupFile       # Ривьера
176.241.141.189 = K:\BackupFile      # Аеромолл

[switch]
94.131.207.175 = true # Амстердам
85.198.150.198 = true # Аполло
176.241.137.147 = false # Бажана
178.136.192.121 = true # Гагарин
185.132.1.213 = true # Глушко
176.241.137.38 = true # Григоренко
93.170.90.195 = true # Днепр
109.237.92.49 = true # Дрим
94.158.153.218 = true # Жуковского
85.159.3.109 = true # Здолбуновская
77.222.159.34 = true # Левобережная
85.159.3.219 = true # Лобановского
91.220.235.171 = true # Метроград
212.90.162.213 = true # Днепр Караван
62.205.146.173 = true # Опера
94.131.244.109 = true # Оушен
217.25.204.224 = true # Район
109.251.113.15 = true # Ретровиль
185.132.0.221 = true # Успенская
195.138.86.14 = true # Филатова
91.228.58.214 = true # Фонтан 1
188.115.185.68 = true # Шампанский
194.28.5.67 = true # Сумы 2
176.241.136.160 = true # РивГош
91.220.235.168 = true # Метроград 2
195.64.232.172 = true # Ривьера
176.241.141.189 = true # Аеромолл
195.138.66.255 = true # Кадор
94.154.222.131 = true # Позняки
31.42.166.8 = true # Каменец-Подольский
77.222.155.140 = true # Каменец-Подольский 2
91.243.199.127 = true # Черкассы